// Code generated by mockery. DO NOT EDIT.

package api

import (
	context "context"

	models "github.com/Arturikou/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockBalanceService is an autogenerated mock type for the BalanceService type
type MockBalanceService struct {
	mock.Mock
}

// GetUserBalance provides a mock function with given fields: ctx, userID
func (_m *MockBalanceService) GetUserBalance(ctx context.Context, userID int) (models.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 models.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.Balance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *MockBalanceService) GetWithdrawals(ctx context.Context, userID int) ([]models.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, withdraw
func (_m *MockBalanceService) Withdraw(ctx context.Context, withdraw models.Withdrawal) error {
	ret := _m.Called(ctx, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Withdrawal) error); ok {
		r0 = rf(ctx, withdraw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBalanceService creates a new instance of MockBalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceService {
	mock := &MockBalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
