env: "local"
log_level: "debug"

http_server:
  address: "localhost:8080"
  idle_timeout: 120s
  read_timeout: 2s
  write_timeout: 2s

db:
  dsn: "postgres://derkachartur:root@localhost:5432/postgres?sslmode=disable"

auth:
  secret_key: "supersecretkey"

