// Code generated by mockery. DO NOT EDIT.

package order

import (
	context "context"

	models "github.com/Arturikou/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

// AddOrder provides a mock function with given fields: ctx, orderNumber, userID
func (_m *MockOrderRepo) AddOrder(ctx context.Context, orderNumber string, userID int) error {
	ret := _m.Called(ctx, orderNumber, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, orderNumber, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID
func (_m *MockOrderRepo) GetOrdersByUserID(ctx context.Context, userID int) ([]models.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersInStatus provides a mock function with given fields: ctx, status
func (_m *MockOrderRepo) GetOrdersInStatus(ctx context.Context, status []models.OrderStatus) ([]models.OrderUpdate, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersInStatus")
	}

	var r0 []models.OrderUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.OrderStatus) ([]models.OrderUpdate, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.OrderStatus) []models.OrderUpdate); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.OrderStatus) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserIDByOrderNumber provides a mock function with given fields: ctx, number
func (_m *MockOrderRepo) GetUserIDByOrderNumber(ctx context.Context, number string) (int, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDByOrderNumber")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, number)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrders provides a mock function with given fields: ctx, orders
func (_m *MockOrderRepo) UpdateOrders(ctx context.Context, orders []models.OrderUpdate) error {
	ret := _m.Called(ctx, orders)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.OrderUpdate) error); ok {
		r0 = rf(ctx, orders)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *MockOrderRepo) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
